dprovision stuff

diff --git a/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_control b/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_control
--- a/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_control
+++ b/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_control
@@ -8,7 +8,6 @@
 #
 #  will store info in REMOT3IT_DIR
 #
-#
 #  remot3.it Inc : https://remot3.it
 #
 #
@@ -19,12 +18,15 @@
 #set -x
 
 #### Settings #####
-VERSION=0.0.7
+VERSION=0.0.8
 MODIFIED="December 4, 2017"
 #
 # Config Dir
 #
 REMOT3IT_DIR="/etc/connectd"
+
+#Raw Provisioning Files Downloaded
+PROVISION_DOWNLOAD="$REMOT3IT_DIR/dfiles"
 #Installed Provisioning files go here (unprovisioned only)
 PROVISION_DEFAULT="$REMOT3IT_DIR/pfiles"
 #created devices are in availabe
@@ -75,18 +77,35 @@ DEBUG=0
 PID=0;
 TIMEIT=0
 FAILTIME=10
-BULK_RETRY_TIME=10
+BULK_RETRY_TIME=20
 #
 # API's
 #
 apiMethod="https://"
-apiVersion="/v26/api"
-apiServer="api.weaved.com"
+apiVersion="/apv/v24.11"
+apiServer="api01.remot3.it"
 #
 # API URL's
 #
 BulkRegisterURL="${apiMethod}${apiServer}${apiVersion}/bulk/registration/register"
 ComponentVersionURL="${apiMethod}${apiServer}${apiVersion}/device/component/version"
+
+#/bulk/registration/device/friendly/configuration/{provisiong_file_id}
+ProjectListURL="${apiMethod}${apiServer}${apiVersion}/bulk/registration/device/friendly/configuration"
+
+#bulk/registration/configuration/{id}/{sec}
+ProvisionConfig="${apiMethod}${apiServer}${apiVersion}/bulk/registration/configuration"
+
+# device/enablement/{provisioning_file_id}
+ProjectEnablementGet="${apiMethod}${apiServer}${apiVersion}/device/enablement"
+
+# Get Provisioning File Link project/provisioning/{provisioning_file_id}
+ProvisionGet="${apiMethod}${apiServer}${apiVersion}/project/provisioning"
+
+# Get provisioning file directly
+# project/provisioning/download/DB0EC490-0D3E-64E0-590A-C379E3FE4FD3
+ProvisionDownloadDirect="${apiMethod}${apiServer}${apiVersion}/project/provisioning/download"
+
 ##### End Settings #####
 
 #
@@ -114,7 +133,7 @@ printf "\n%s\n\n\n" "$man_text"
 usage()
 {
     echo "Usage: $0 command " >&2
-    echo "  commands : types typesl status enable disable start stop restart bprovision update updatedeb reset" >&2
+    echo "  commands : types typesl status enable disable start stop restart dprovision bprovision update updatedeb reset" >&2
     echo "Version $VERSION Build $MODIFIED" >&2
     exit 1 
 }
@@ -172,6 +191,10 @@ get_registration_data()
         hardware_id=$(cat /sys/class/net/$REG_ID_ADAPTER/address | sed s/://g)
         registration_key=$(cat /sys/class/net/$REG_KEY_ADAPTER/address | sed s/://g) 
     fi
+
+    registration_key="FOOBAR"
+    hardware_id="DEO_POOLED_1"
+
     if [ $VERBOSE -gt 0 ]; then
         printf "Hardware ID is %s registration key is %s\n" $hardware_id $registration_key
     fi
@@ -454,7 +477,7 @@ check_auth_cache()
 
 
 #
-# match_device 
+# projectsmatch_device 
 #   match the passed device name to the array and return the index if found or 0 if not
 #   if found device_state and device_address are set
 #
@@ -639,6 +662,205 @@ list()
 }
 
 
+#
+# write_config [name] [data]
+#
+write_config()
+{
+    if [ $VERBOSE -gt 0 ]; then printf "write config for %s \n" "$1" ; fi
+    timestamp=$(jsonvalx "$2" "timestamp")
+    enabled=$(jsonvalx "$2" "enabled")
+    content_ip=$(jsonvalx "$2" "content_ip")
+    content_port=$(jsonvalx "$2" "content_port")
+    content_type=$(jsonvalx "$2" "content_type")
+    content_test=$(jsonvalx "$2" "content_test")
+    echo "timestamp $timestamp" > "$PROVISION_DOWNLOAD/$1.conf"
+    if [ -n "$enabled" ]; then
+        echo "enabled $enabled" >> "$PROVISION_DOWNLOAD/$1.conf"
+    else
+        echo "enabled 1" >> "$PROVISION_DOWNLOAD/$1.conf"
+    fi
+    #
+    if [ -n "$content_type" ]; then
+        echo "application_type $content_type" >> "$PROVISION_DOWNLOAD/$1.conf"
+    fi
+    if [ -n "$content_port" ]; then
+        echo "proxy_dest_port $content_port" >> "$PROVISION_DOWNLOAD/$1.conf"
+    fi
+    if [ -n "$content_ip" ]; then
+        echo "proxy_dest_ip $content_ip" >> "$PROVISION_DOWNLOAD/$1.conf"
+    fi
+    if [ -n "$content_test" ]; then
+        echo "content_test $content_test" >> "$PROVISION_DOWNLOAD/$1.conf"
+    fi
+}
+
+#
+#
+#
+generate_pfile()
+{
+    if [ $VERBOSE -gt 0 ]; then printf "generate pfile for %s \n" "$1" ; fi
+	# delete pfile if it exists 
+    if [ -f "$PROVISION_DEFAULT/$1" ]; then
+    	rm "$PROVISION_DEFAULT/$1"
+    fi
+    # Generate pfile
+    cat "$PROVISION_DOWNLOAD/$1" >> "$PROVISION_DEFAULT/$1"
+    cat "$PROVISION_DOWNLOAD/$1.conf" >> "$PROVISION_DEFAULT/$1"
+    echo "#####-#####" >> "$PROVISION_DEFAULT/$1"
+}
+
+#
+# update_afile() update an active file
+#
+update_afile()
+{
+    if [ $VERBOSE -gt 0 ]; then printf "update available file for %s\n" "$1" ; fi
+    # disabled, check if we need to disable it from startup
+    if [ -f "$DEVICES_AVAILABLE/$1" ]; then
+		if [ -f "$PROVISION_DEFAULT/$i" ]; then
+			# get user config
+			dynamic=$(cat "$DEVICES_AVAILABLE/$1" | sed -e "1,/"#####-#####"/d")
+			cp "$PROVISION_DEFAULT/$1" "$DEVICES_AVAILABLE/$1"
+			echo $dynamic >> "$DEVICES_AVAILABLE/$1"
+		fi	
+	fi
+}
+
+#
+# download the config for a provisioning file
+# dconfig [id] [secret]
+#
+dconfig()
+{
+    #download the config fir th passed provsioning file
+    resp2=$(curl -s -S -X GET -H "content-type:application/json" "$ProvisionConfig/$1/$2/")
+    status=$(jsonvalx "$resp2" "status")
+    if [ "$status" = "true" ]; then
+    	#
+    	# get timestamp and enable
+    	timestamp=$(jsonvalx "$resp2" "timestamp")
+    	enabled=$(jsonvalx "$resp2" "enabled")
+    	#
+    	# check if config file is there, if not, check if we are enabled
+    	if [ ! -f "$PROVISION_DOWNLOAD/$i.conf" ]; then
+    		# conf file does not exit
+        	if [ $VERBOSE -gt 0 ]; then printf "config file does not exist\n" ; fi
+        	if [ $enabled = "1" ]; then
+        	    # enabled, generate config file and pfiles 
+                write_config "$i" "$resp2"
+                # Generate
+                generate_pfile "$1"
+				#
+            else
+                # not enabled, do nothing, 
+                if [ $VERBOSE -gt 0 ]; then printf "diabled do nothing\n" ; fi
+        	fi
+    	else
+    		# check timestamp with grep
+    		if [ $enabled = "1" ]; then
+    		    # check timestamp with grep
+        	    result=$(grep "$timestamp" "$PROVISION_DOWNLOAD/$i.conf")
+        	    if [ "$?" = "1" ]; then
+        		    if [ $VERBOSE -gt 0 ]; then printf "timestamp not same, update\n" ; fi
+        		    #
+                    # need to generate conf file and pfile, update available
+                    write_config "$i" "$resp2"
+                    #
+                    # Generate new pfile
+                    generate_pfile "$1"
+					#
+					# update the active file
+					update_afile "$1"
+
+           	    else
+            	    if [ $VERBOSE -gt 0 ]; then printf "timestamp same, no update\n" ; fi
+			    fi
+			else
+			    # disabled, check if we need to disable it from startup
+                if [ -e "$DEVICES_ACTIVE/$1" ]; then
+                    stopit "$1"
+                    rm "$DEVICES_ACTIVE/$1"
+                fi
+			fi
+		fi
+    else
+    	if [ $VERBOSE -gt 0 ]; then printf "Provisioning Config Failed (%s)\n" $status ; fi
+    fi
+}
+
+#
+#download provsioning and configurating files
+# update configuration if exists and are changed
+#
+dprovision()
+{
+    ret=1
+    rc=1
+    if [ "$#" -ne 2 ]; then
+    #if [ -z "${@}" ]; then
+        ret=3
+        echo "ERROR: dprovision requires two parameters, a project ID and a secret."
+    else
+		#
+		# get the list of project ID's for the product
+		# ProjectListURL		
+		#ProjectEnablement
+        #ProjectListURL
+		resp=$(curl -s -S -X GET -H "content-type:application/json" "$ProjectListURL/$1/$2/")
+        # parse response "status"
+        status=$(jsonvalx "$resp" "status")
+        if [ "$status" = "true" ]; then
+            #
+            # parse out
+            projects=$(jsonvalx "$resp" "projects")
+            #
+            # replace , with spaces
+            #lines=$(echo "$projects" | sed  's/,/ /g' )
+            old_IFS=${IFS}
+            IFS=','
+            for i in $projects; do
+                if [ $VERBOSE -gt 0 ]; then printf 'Looping over %s\n' "$i" ; fi\
+                # check if it exists, download if not
+                if [ ! -f "$PROVISION_DOWNLOAD/$i" ]; then    
+                    if [ $VERBOSE -gt 0 ]; then echo "need to download" ; fi
+                    #
+                    # download and store in directory
+                    # ProjectEnablementGet
+                    # in this case we write out the file and check the return code
+                    resp2=$(curl -s -S --write-out %{http_code} -X GET -H "content-type:application/json" \
+                                    -o "$PROVISION_DOWNLOAD/$i.tmp" "$ProvisionDownloadDirect/$i")
+
+                    if [ "$resp2" = "200" ]; then
+                        # if retrun code is 200 we keep the file
+						mv "$PROVISION_DOWNLOAD/$i.tmp" "$PROVISION_DOWNLOAD/$i"
+						if [ $VERBOSE -gt 0 ]; then printf "downloaded provsioning ok (%s)\n" $resp2 ; fi						
+                    else
+                        # do not keep, bad
+                        rm "$PROVISION_DOWNLOAD/$i.tmp"
+                        if [ $VERBOSE -gt 0 ]; then printf "Failed to download provsioning file (%s)\n" $resp2 ; fi
+                    fi
+                else
+                    # do nothing already downloaded
+                    if [ $VERBOSE -gt 0 ]; then printf "Provisioning File %s already downloaded\n" $i ; fi
+                fi
+
+                #if provision exists lets try to get the config
+                if [ -f "$PROVISION_DOWNLOAD/$i" ]; then
+                    dconfig "$i" "$2" 
+                fi    
+            done
+
+            IFS=${old_IFS}
+            
+        else
+            echo "failed"
+        fi
+	fi
+}
+
+
 #bulk provision a specific pfile do not call directly call bprovsion()
 bprovisionit()
 {
@@ -659,7 +881,8 @@ bprovisionit()
 		while : 
 		do
         	# make curl call
-        	data='{"project_id":"'$project_id'","hardware_id" : "'$hardware_id'", "registration_key" : "'$registration_key'"}'
+        	#data='{"project_id":"'$project_id'","hardware_id" : "'$hardware_id'", "registration_key" : "'$registration_key'"}'
+        	data='{"queue_name":"WeavedTaskQueue_test","project_id":"'$project_id'","hardware_id" : "'$hardware_id'", "registration_key" : "'$registration_key'"}'
 
         	resp=$(curl -s -S -X POST -H "content-type:application/json" --data "$data" $BulkRegisterURL )
 
@@ -1074,6 +1297,10 @@ case "$command" in
     "bprovision")
         shift
         bprovision $@
+        ;;
+    "dprovision")
+        shift
+        dprovision $@
         ;;
     "enable")
         shift
