Updates for OEM ARM package and self-extracting archive.

diff --git a/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_options b/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_options
--- a/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_options
+++ b/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_options
@@ -3,13 +3,13 @@
 #===================================
 MODIFIED="January 19, 2018"
 #===================================
-BUILDDATE="Sat Jan 20 20:26:34 PST 2018"    
+BUILDDATE="Sun Jan 21 14:31:40 PST 2018"    
 #===================================
 # set DEBUG to 1 to enable debugging messages
 DEBUG="0"
 #===================================
 # BASEDIR is root on many systems. If so, leave it blank.
-BASEDIR=
+BASEDIR=/home/user    
 #===================================
 # BIN_DIR is default path for executables.  We install connectd scripts and binaries here.
 BIN_DIR="$BASEDIR"/usr/bin
@@ -30,16 +30,34 @@ LOG_DIR=/var/log
 # same as the HWID, or a constant for all devices.
 #
 REG_DEBUG=0
-# if desired, customize these expressions for your platform, e.g to pick up the IMEI
+# if desired, customize these expressions for your platform, 
+# e.g to pick up the IMEI rather than the network adapter MAC address.
 # network adapter name to use for the HWID, if desired
 REG_ID_ADAPTER="wlan0"
 #REG_ID_ADAPTER="enp3s0"
-hardware_id="$(cat /sys/class/net/$REG_ID_ADAPTER/address | sed s/://g)"
+id_address=/sys/class/net/"$REG_ID_ADAPTER"/address
+
+if [ -e "$id_address" ]; then
+    hardware_id="$(cat $id_address | sed s/://g)"
+else
+    echo "Error! Check expression for hardware_id in connectd_options."
+    echo "Exiting..."
+    exit 1
+fi
 
 # network adapter name to use for the Registration Key, if desired
 REG_KEY_ADAPTER="eth0"
 #REG_KEY_ADAPTER="wlp2s0"
-registration_key="$(cat /sys/class/net/$REG_KEY_ADAPTER/address | sed s/://g)"
+
+rk_address=/sys/class/net/"$REG_KEY_ADAPTER"/address
+
+if [ -e "$rk_address" ]; then
+    registration_key="$(cat $rk_address | sed s/://g)"
+else
+    echo "Error! Check expression for registration_key in connectd_options."
+    echo "Exiting..."
+    exit 1
+fi
 
 #===================================
 # Configuration Folder Variables
