added overrides for hardware id and registration key
moved custom code to end of connectd_options

diff --git a/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_options b/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_options
--- a/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_options
+++ b/Raspbian deb/1.3-08/connectd_1.3-08/usr/bin/connectd_options
@@ -19,47 +19,6 @@ LOG_DIR=/var/log
 # folders and files
 # these folders are not the same as used by Bulk Registration
 #===================================
-if [ "$BULK_REG" = 1 ]; then
-# Bulk Registration Variables
-#===================================
-# set reg debug = 1 to debug registration
-#===================================
-# The expressions below are supplied to provide the Bulk Registration API with the
-# Hardware ID (HWID) and Registration Key needed to identify the unique product
-# Hardware ID but be unique across the remot3.it system
-# Registration can be another unique value readable from the command line, the
-# same as the HWID, or a constant for all devices.
-#
-REG_DEBUG=0
-# if desired, customize these expressions for your platform, 
-# e.g to pick up the IMEI rather than the network adapter MAC address.
-# network adapter name to use for the HWID, if desired
-REG_ID_ADAPTER="wlan0"
-#REG_ID_ADAPTER="enp3s0"
-id_address=/sys/class/net/"$REG_ID_ADAPTER"/address
-
-if [ -e "$id_address" ]; then
-    hardware_id="$(cat $id_address | sed s/://g)"
-else
-    echo "Error! Check expression for hardware_id in connectd_options."
-    echo "Exiting..."
-    exit 1
-fi
-
-# network adapter name to use for the Registration Key, if desired
-REG_KEY_ADAPTER="eth0"
-#REG_KEY_ADAPTER="wlp2s0"
-
-rk_address=/sys/class/net/"$REG_KEY_ADAPTER"/address
-
-if [ -e "$rk_address" ]; then
-    registration_key="$(cat $rk_address | sed s/://g)"
-else
-    echo "Error! Check expression for registration_key in connectd_options."
-    echo "Exiting..."
-    exit 1
-fi
-fi
 
 #===================================
 # Configuration Folder Variables
@@ -135,5 +94,93 @@ CHECKFORDEB="0"
 # The PACKAGE variable sets the Debian package name.  Only relevant if CHECKFORDEB is set to 1.
 PACKAGE="connectd"
 #===================================
+
+
+#===================================
+# IMPORTANT CONFIG BELOW
+#
+#if BULK REG then we need hardware_id and registration_key, this is setup to use
+#the WLAN0 adapter MAC address  as the hardware_id and the eth0 as the registration_key
+#this is likely not what you want on your system.  hardware_id must be unique on the
+#remot3.it system, your device will be rejected if not unique.
+#
+#Good hardware_id's are MAC+Random, UUID, IMEI etc.  You may want to pre or pospend
+#a static string onto IMEI or MAC addresses to know that you are unique on your 
+#product line, we are not sure if you can trust MAC addresses to be unique.
+#
+#Registration keys should be uniqe per Hardware ID, though it is not required. 
+#Pridictable registration keys are prone to cause problems if the hardware ID's
+#are also predictable.  Registration keys can be a different MAC than the 
+#hardware_id, preprogrammed random value, hash of hardware_id+secret, or any
+#other value you wish to use.   Remot3.it does not care as long as you provide
+#us the unique hardware_id and registration key for registration.
+#
+#registraiton key hash example:
+#company secret = "xyzzy"
+#registration_key=sha256(hardware_id,"xyzzy")
+#
+#for testing you can create a harware_id.txt and a registraiton_key.txt in your
+#/etc/connectd directory and this software will use these values to override
+#the programatic methods used below.   Just make sure these files do not exist
+#in production unless you are using them to write unique values at production
+#time.
+#
+
+#
+if [ "$BULK_REG" = 1 ]; then
+# Bulk Registration Variables
+#===================================
+# set reg debug = 1 to debug registration
+#===================================
+# The expressions below are supplied to provide the Bulk Registration API with the
+# Hardware ID (HWID) and Registration Key needed to identify the unique product
+# Hardware ID but be unique across the remot3.it system
+# Registration can be another unique value readable from the command line, the
+# same as the HWID, or a constant for all devices.
+#
+REG_DEBUG=0
+# if desired, customize these expressions for your platform, 
+# e.g to pick up the IMEI rather than the network adapter MAC address.
+# network adapter name to use for the HWID, if desired
+REG_ID_ADAPTER="wlan0"
+#REG_ID_ADAPTER="enp3s0"
+HW_ID_OVERRIDE_FILE="${CONNECTD_DIR}/hardware_id.txt"
+
+if [ -e $HW_ID_OVERRIDE_FILE ]; then
+    hardware_id="$(cat $HW_ID_OVERRIDE_FILE)"
+else
+    id_address=/sys/class/net/"$REG_ID_ADAPTER"/address
+
+    if [ -e "$id_address" ]; then
+        hardware_id="$(cat $id_address | sed s/://g)"
+    else
+        echo "Error! Check expression for hardware_id in connectd_options."
+        echo "Exiting..."
+        exit 1
+    fi
+fi
+
+# network adapter name to use for the Registration Key, if desired
+REG_KEY_ADAPTER="eth0"
+#REG_KEY_ADAPTER="wlp2s0"
+REG_KEY_OVERRIDE_FILE="${CONNECTD_DIR}/registration_key.txt"
+
+if [ -e $REG_KEY_OVERRIDE_FILE ]; then
+    registration_key="$(cat $REG_KEY_OVERRIDE_FILE)"
+else
+	rk_address=/sys/class/net/"$REG_KEY_ADAPTER"/address
+
+	if [ -e "$rk_address" ]; then
+   		registration_key="$(cat $rk_address | sed s/://g)"
+	else
+   		echo "Error! Check expression for registration_key in connectd_options."
+   		echo "Exiting..."
+   		exit 1
+	fi
+fi
+
+### End if [ "$BULK_REG" = 1 ]
+fi
+
 
 
