updated schannel binary to version 0.4

diff --git a/Ubuntu_deb/weavedconnectd_1.3-06_x86/weavedconnectd_1.3-06_x86/usr/bin/remot3_script_lib b/Ubuntu_deb/weavedconnectd_1.3-06_x86/weavedconnectd_1.3-06_x86/usr/bin/remot3_script_lib
--- a/Ubuntu_deb/weavedconnectd_1.3-06_x86/weavedconnectd_1.3-06_x86/usr/bin/remot3_script_lib
+++ b/Ubuntu_deb/weavedconnectd_1.3-06_x86/weavedconnectd_1.3-06_x86/usr/bin/remot3_script_lib
@@ -6,7 +6,7 @@
 #
 # 
 #----------------------------------------------------------
-VERSION="0.0.4"
+VERSION="0.0.5"
 MODIFIED="June 30, 2016"
 VERBOSE=1
 
@@ -225,4 +225,53 @@ REBOOTFILE=/root/.remot3.it/reboot.sh
     /sbin/reboot
 }
 
+##############################################################################
+# Read timeout for wget, default is 900 seconds.  set shorter for testing.
+READTIMEOUT=120
+READRETRIES=5
 
+# constants for retry logic
+HOUR=$(expr 60 \* 60)
+DAY=$(expr $HOUR \* 24)
+WEEK=$(expr $DAY \* 7)
+
+download_with_retry()
+{
+    finished=0
+    error=0
+    log "$1"
+
+    filename=$(echo "$1" | awk '{ print $3 }')
+    log "$filename"
+
+    # remove any possible existing file of same name we are about to download
+    if [ -e "$filename" ]; then
+        log "Removing pre-existing $filename"
+        rm "$filename"
+    fi
+
+    START=$(date +%s)
+    log "Download started at $START"
+
+    while [ $finished -eq 0 ]; do
+    wget_o=$(wget -c --read-timeout="$READTIMEOUT" -t $READRETRIES --no-check-certificate $1 )
+    retval=$?
+ 
+    if [ $retval -eq 0 ]; then
+        finished=1
+	else
+	    if [ $retval -eq 4 ]; then
+		NOW=$(date +%s)
+		DELTA=$((NOW - START))
+		log "$filename: wget returned $retval at $time, elapsed = $DELTA"
+
+            if [ $DELTA -gt $WEEK ]; then exit; fi
+            sleep 5
+	    else
+		finished=1
+                error=$retval
+            fi
+	fi
+     done
+     echo "$filename"
+}
